Repository creativeplatform/monorepo, pull requests merged in 2023-07, with the labels that each got.

#65 IPFS Errors Fix
  Creative/apps/creative-tv/package.json
  Creative/apps/creative-tv/src/components/CreateAndViewAsset.tsx
  Creative/apps/creative-tv/src/components/MintNftVideo.tsx
  Creative/apps/creative-tv/src/components/UploadVideoAsset.tsx
  Creative/apps/creative-tv/src/components/WagmiNft.tsx
  Creative/apps/creative-tv/src/components/videoNftAbi.tsx
  Creative/apps/creative-tv/src/hooks/useDeployDrop.tsx
  Creative/apps/creative-tv/src/hooks/useInitThirdweb.tsx
  Creative/apps/creative-tv/src/pages/discover/[id].tsx
  Creative/apps/creative-tv/src/pages/index.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/index.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/upload.tsx
  Creative/apps/creative-tv/src/providers/Web3.tsx
  Creative/apps/creative-tv/src/utils/config.ts
  Creative/package.json
  Creative/yarn.lock
Labels: bugfix

#67 Bug: Wallet Signing is Looping
  Creative/apps/creative-tv/.sample.env
  Creative/apps/creative-tv/package.json
  Creative/apps/creative-tv/src/components/CreateAndViewAsset.tsx
  Creative/apps/creative-tv/src/components/HeroSection.tsx
  Creative/apps/creative-tv/src/components/MintNftVideo.tsx
  Creative/apps/creative-tv/src/components/WagmiNft.tsx
  Creative/apps/creative-tv/src/components/layout/Header.tsx
  Creative/apps/creative-tv/src/hooks/useDeployDrop.tsx
  Creative/apps/creative-tv/src/pages/_document.tsx
  Creative/apps/creative-tv/src/utils/config.ts
  Creative/apps/creative-works-app/.prettierignore
  Creative/apps/creative-works-app/.vscode/extensions.json
  Creative/apps/creative-works-app/.vscode/settings.json
  Creative/apps/creative-works-app/LICENSE.md
  Creative/apps/creative-works-app/README.md
  Creative/apps/creative-works-app/application/.env.example
  Creative/apps/creative-works-app/application/.eslintrc.json
  Creative/apps/creative-works-app/application/.gitignore
  Creative/apps/creative-works-app/application/LICENSE.md
  Creative/apps/creative-works-app/application/README.md
  Creative/apps/creative-works-app/application/components/Navbar.tsx
  Creative/apps/creative-works-app/application/components/button.tsx
  Creative/apps/creative-works-app/application/components/checkbox.tsx
  Creative/apps/creative-works-app/application/components/demo/ContractInteraction.tsx
  Creative/apps/creative-works-app/application/components/demo/DecentralizedStorage.tsx
  Creative/apps/creative-works-app/application/components/demo/UserAuthentication.tsx
  Creative/apps/creative-works-app/application/components/demo/WalletConnection.tsx
  Creative/apps/creative-works-app/application/const/chains.ts
  Creative/apps/creative-works-app/application/const/contracts.ts
  Creative/apps/creative-works-app/application/lib/utils.ts
  Creative/apps/creative-works-app/application/next-env.d.ts
  Creative/apps/creative-works-app/application/next.config.js
  Creative/apps/creative-works-app/application/package.json
  Creative/apps/creative-works-app/application/pages/_app.tsx
  Creative/apps/creative-works-app/application/pages/api/auth/[...thirdweb].ts
  Creative/apps/creative-works-app/application/pages/api/secret.ts
  Creative/apps/creative-works-app/application/pages/index.tsx
  Creative/apps/creative-works-app/application/postcss.config.js
  Creative/apps/creative-works-app/application/public/discord.png
  Creative/apps/creative-works-app/application/public/favicon.ico
  Creative/apps/creative-works-app/application/public/github.png
  Creative/apps/creative-works-app/application/public/hero-fade.png
  Creative/apps/creative-works-app/application/public/logo.png
  Creative/apps/creative-works-app/application/public/twitter.png
  Creative/apps/creative-works-app/application/styles/globals.css
  Creative/apps/creative-works-app/application/tailwind.config.js
  Creative/apps/creative-works-app/application/thirdweb.json
  Creative/apps/creative-works-app/application/tsconfig.json
  Creative/apps/creative-works-app/application/yarn.lock
  Creative/apps/creative-works-app/contracts/.gitignore
  Creative/apps/creative-works-app/contracts/README.md
  Creative/apps/creative-works-app/contracts/contracts/Greeter.sol
  Creative/apps/creative-works-app/contracts/hardhat.config.ts
  Creative/apps/creative-works-app/contracts/package.json
  Creative/apps/creative-works-app/contracts/test/Greeter.ts
  Creative/apps/creative-works-app/contracts/tsconfig.json
  Creative/apps/creative-works-app/contracts/yarn.lock
  Creative/yarn.lock
Labels: bug, enhancement, help wanted

#68 Hunters workshop/metokens integration
  Creative/apps/creative-tv/next.config.js
  Creative/apps/creative-tv/src/components/MeTokenCreationForm.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/index.tsx
  Creative/apps/creative-tv/src/utils/config.ts
  Creative/apps/creative-tv/src/utils/fetchers/createMeToken.ts
  Creative/apps/creative-tv/src/utils/fetchers/metokens.ts
  Creative/package.json
  Creative/yarn.lock
Labels: enhancement, good first issue

#69 added mobile responsiveness
  Creative/apps/creative-tv/src/components/layout/Header.tsx
Labels: enhancement, good first issue, bugfix

#70 Transfer Tokens
  Creative/apps/creative-tv/src/components/layout/Header.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/index.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/transfer.tsx
  Creative/apps/creative-tv/src/utils/config.d.ts
  Creative/apps/creative-tv/src/utils/config.d.ts.map
  Creative/apps/creative-tv/src/utils/config.js
  Creative/apps/creative-tv/src/utils/config.ts
  Creative/apps/thirdweb/token-transfer/.gitignore
  Creative/apps/thirdweb/token-transfer/README.md
  Creative/apps/thirdweb/token-transfer/contracts/Contract.sol
  Creative/apps/thirdweb/token-transfer/hardhat.config.js
  Creative/apps/thirdweb/token-transfer/package.json
  Creative/apps/thirdweb/token-transfer/yarn.lock
  Creative/package.json
  Creative/packages/ui/BalanceCard.d.ts
  Creative/packages/ui/BalanceCard.d.ts.map
  Creative/packages/ui/BalanceCard.js
  Creative/packages/ui/BalanceCard.tsx
  Creative/packages/ui/Events.d.ts
  Creative/packages/ui/Events.d.ts.map
  Creative/packages/ui/Events.js
  Creative/packages/ui/Events.tsx
  Creative/packages/ui/FeatureCard.d.ts
  Creative/packages/ui/FeatureCard.d.ts.map
  Creative/packages/ui/FeatureCard.js
  Creative/packages/ui/FeatureCard.tsx
  Creative/packages/ui/TokenBalance.d.ts
  Creative/packages/ui/TokenBalance.d.ts.map
  Creative/packages/ui/TokenBalance.js
  Creative/packages/ui/TokenBalance.tsx
  Creative/packages/ui/TokenSelection.d.ts
  Creative/packages/ui/TokenSelection.d.ts.map
  Creative/packages/ui/TokenSelection.js
  Creative/packages/ui/TokenSelection.tsx
  Creative/packages/ui/XferButton.d.ts
  Creative/packages/ui/XferButton.d.ts.map
  Creative/packages/ui/XferButton.js
  Creative/packages/ui/XferButton.tsx
  Creative/packages/ui/XferCard.d.ts
  Creative/packages/ui/XferCard.d.ts.map
  Creative/packages/ui/XferCard.js
  Creative/packages/ui/XferCard.tsx
  Creative/packages/ui/tsconfig.json
  Creative/yarn.lock
Labels: enhancement

#71 hamburger changes
  Creative/apps/creative-tv/src/components/layout/Header.tsx
Labels: good first issue, bugfix

#74 Transfer
  Creative/apps/creative-tv/src/components/Carousel.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/index.tsx
  Creative/packages/ui/XferCard.d.ts.map
  Creative/packages/ui/XferCard.js
  Creative/packages/ui/XferCard.tsx
Labels: bugfix

#73 Update README.md
  README.md
Labels: documentation
