Repository creativeplatform/monorepo, pull requests merged in 2023-08, with the labels that each got.

#75 Hunters workshop/metokens integration - WIP
  Creative/apps/creative-tv/src/components/MeTokenCreationForm.tsx
  Creative/apps/creative-tv/src/components/MemberCard.tsx
  Creative/apps/creative-tv/src/pages/_app.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/index.tsx
  Creative/apps/creative-tv/src/utils/config.ts
  Creative/apps/creative-tv/src/utils/fetchers/createMeToken.ts
  Creative/package.json
  Creative/yarn.lock
Labels: enhancement, good first issue

#76 fixes for type stuff
  Creative/apps/creative-tv/src/components/MemberCard.tsx
  Creative/apps/creative-tv/src/hooks/useLivepeerClient.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/index.tsx
  Creative/apps/creative-tv/src/pages/unauthorized.tsx
  Creative/apps/creative-tv/src/utils/config.d.ts
  Creative/apps/creative-tv/src/utils/config.d.ts.map
  Creative/apps/creative-tv/src/utils/config.js
  Creative/apps/creative-tv/wagmi.config.ts
Labels: bugfix

#82 Feat/livepeer video nft minting dag jose
  Creative/apps/creative-tv/.eslintrc.json
  Creative/apps/creative-tv/package.json
  Creative/apps/creative-tv/src/components/CreateAndViewAsset.tsx
  Creative/apps/creative-tv/src/components/MintNftVideo.tsx
  Creative/apps/creative-tv/src/components/UpdateVideoAsset.tsx
  Creative/apps/creative-tv/src/components/UploadVideoAsset.tsx
  Creative/apps/creative-tv/src/components/WagmiNft.tsx
  Creative/apps/creative-tv/src/components/hoc/ErrorBoundary.tsx
  Creative/apps/creative-tv/src/components/layout/Header.tsx
  Creative/apps/creative-tv/src/components/layout/index.tsx
  Creative/apps/creative-tv/src/components/videoPreview.tsx
  Creative/apps/creative-tv/src/pages/_app.tsx
  Creative/apps/creative-tv/src/pages/_document.tsx
  Creative/apps/creative-tv/src/pages/profile/[address]/upload.tsx
  Creative/apps/creative-tv/src/utils/config.d.ts
  Creative/apps/creative-tv/src/utils/config.d.ts.map
  Creative/apps/creative-tv/src/utils/config.js
  Creative/apps/creative-tv/src/utils/config.ts
  Creative/apps/creative-tv/src/utils/constant.ts
  Creative/apps/creative-tv/src/utils/formatString/index.ts
  Creative/package.json
  Creative/yarn.lock
Labels: enhancement, good first issue, bugfix
